folio-org/mod-erm-usage

- descriptors/ModuleDescriptor-template.json
- mod-erm-usage-client/pom.xml
- mod-erm-usage-server/pom.xml
- mod-erm-usage-server/src/main/java/org/folio/rest/impl/AggregatorSettingsAPI.java
- mod-erm-usage-server/src/main/java/org/folio/rest/impl/UsageDataProvidersAPI.java
- mod-erm-usage-server/src/main/java/org/folio/rest/util/AttributeNameAdder.java
- mod-erm-usage-server/src/main/java/org/folio/rest/util/nameresolver/AggregatorNameResolver.java
- mod-erm-usage-server/src/main/java/org/folio/rest/util/nameresolver/VendorNameResolver.java
- mod-erm-usage-server/src/test/java/org/folio/mod_erm_usage_test/AggregatorSettingsIT.java
- mod-erm-usage-server/src/test/java/org/folio/mod_erm_usage_test/CounterReportIT.java
- mod-erm-usage-server/src/test/java/org/folio/mod_erm_usage_test/UsageDataProvidersIT.java
- mod-erm-usage-server/src/test/resources/__files/vendor.json
- pom.xml
- ramls/examples/udproviders.sample
- ramls/examples/udproviders2.sample
- ramls/examples/udproviders_collection.sample
- ramls/schemas/udprovider.json
- ramls/usagedataproviders.raml
- It is possible to define aggregator and direct access via usage data provider in parallel. The used option is defined by flag.
- Resolve and store name of vendor and aggregator locally.
> Restructure usage data provider

- .gitignore
- descriptors/ModuleDescriptor-template.json
- mod-erm-usage-server/pom.xml
- mod-erm-usage-server/src/main/java/org/folio/rest/impl/AggregatorSettingsAPI.java
- mod-erm-usage-server/src/main/java/org/folio/rest/util/ExportObject.java
- mod-erm-usage-server/src/test/java/org/folio/mod_erm_usage_test/AggregatorSettingsIT.java
- mod-erm-usage-server/src/test/java/org/folio/rest/impl/AggregatorSettingsIT.java
- mod-erm-usage-server/src/test/java/org/folio/rest/impl/CounterReportCsvIT.java
- mod-erm-usage-server/src/test/java/org/folio/rest/impl/CounterReportIT.java
- mod-erm-usage-server/src/test/java/org/folio/rest/impl/CounterReportUploadIT.java
- mod-erm-usage-server/src/test/java/org/folio/rest/impl/UsageDataProvidersIT.java
- mod-erm-usage-server/src/test/resources/exportcredentials/aggregators.json
- mod-erm-usage-server/src/test/resources/exportcredentials/providers.json
- ramls/aggregatorsettings.raml
> MODEUS-7, MODEUS-10

- .dockerignore
- .gitignore
- .gitlab-ci.yml
- Dockerfile
- docker-compose.yml
- ubl/Dockerfile
- ubl/Readme.md
- ubl/helmchart/.helmignore
- ubl/helmchart/Chart.yaml
- ubl/helmchart/templates/_helpers.tpl
- ubl/helmchart/templates/app.configmap.yaml
- ubl/helmchart/templates/app.deployment.yaml
- ubl/helmchart/templates/app.service.yaml
- ubl/helmchart/templates/db.configmap.yaml
- ubl/helmchart/templates/db.deployment.yaml
- ubl/helmchart/templates/db.service.yaml
- ubl/helmchart/templates/secret.yaml
- ubl/helmchart/values.yaml
This PR adds required changes in order to integrate this module in the deployment-workflow of UBL. It consists of
* `docker-compose.yml`: only needed for locally testing deployment functionality (devops resource)
* `.gitlab-ci.yml`: GitLab-CI  pipeline-receipe for building JAR and docker-image, publishing image and deploying via helm to kubernetes
* `ubl/helmchart`: the Helm-Chart needed to deploy the module via helm
* `ubl/Dockerfile`: the Dockerfile to create a docker-image which satisfys the needs of the deployment-workflow
* `ubl/Readme.md`: workflow documentation
> enabled GitLab-CI for UBL-Workflow

- .gitlab-ci.yml
- ubl/Dockerfile
- ubl/Readme.md
- ubl/helmchart/Chart.yaml
- ubl/helmchart/templates/app.configmap.yaml
- ubl/helmchart/values.yaml
* auto-setup id  in image-build-job
* removed unused proxy-setup
* updated docs
> removes requirement to setup module id separate

- .gitlab-ci.yml
- docker-compose.yml
- ubl/helmchart/templates/app.configmap.yaml
- ubl/helmchart/values.yaml
* removes service- and install-id from staging-job
* adds namespace to service-url
> fixes staging deployment

- .gitlab-ci.yml
Changed CI settings.
- alpha images will be tagged with 'latest'.
- switched publish_staging and publish_production to manual
> Refactor CI settings.

- .gitlab-ci.yml
Had to replace the branch refs with 'latest'.
> Corrected tag names for alpha deployment.

- mod-erm-usage-server/src/main/java/org/folio/rest/util/ModuleVersion.java
- mod-erm-usage-server/src/main/resources/templates/db_scripts/aggregatorsettings_triggers.sql
- mod-erm-usage-server/src/main/resources/templates/db_scripts/counterreports_triggers.sql
- mod-erm-usage-server/src/main/resources/templates/db_scripts/migration/usage_data_providers.sql
- mod-erm-usage-server/src/main/resources/templates/db_scripts/schema.json
- mod-erm-usage-server/src/main/resources/templates/db_scripts/usagedataproviders_triggers.sql
- mod-erm-usage-server/src/test/java/org/folio/rest/impl/AggregatorSettingsIT.java
- mod-erm-usage-server/src/test/java/org/folio/rest/impl/CounterReportCsvIT.java
- mod-erm-usage-server/src/test/java/org/folio/rest/impl/CounterReportIT.java
- mod-erm-usage-server/src/test/java/org/folio/rest/impl/CounterReportUploadIT.java
- mod-erm-usage-server/src/test/java/org/folio/rest/impl/UsageDataProvidersIT.java
- mod-erm-usage-server/src/test/java/templates/db_scripts/SQLTriggersIT.java
- pom.xml
Add migrate script to reflect schema changes.
> Modeus 44 q4 db update

- descriptors/ModuleDescriptor-template.json
- mod-erm-usage-server/src/main/java/org/folio/rest/impl/CounterReportAPI.java
- mod-erm-usage-server/src/test/java/org/folio/rest/impl/CounterReportSortedIT.java
- ramls/counterreports.raml
- ramls/examples/counterreports_sorted.sample
- ramls/schemas/counterreports_sorted.json
Sort counter reports by year and report type in backend instead of frontend.
This hopefully fixes the browser freeze.
> Uieus 134 fix browser freeze

- descriptors/ModuleDescriptor-template.json
- mod-erm-usage-server/src/main/java/org/folio/rest/impl/ErmUsageFilesAPI.java
- mod-erm-usage-server/src/main/java/org/folio/rest/model/ErmUsageFile.java
- mod-erm-usage-server/src/main/resources/templates/db_scripts/schema.json
- mod-erm-usage-server/src/test/java/org/folio/rest/impl/ErmUsageFilesIT.java
- ramls/files.raml
Add endpoint to upload files. Needed for uploading of non-counter usage statistics.
> Modeus 59 files endpoint

- descriptors/ModuleDescriptor-template.json
- ramls/aggregatorsettings.raml
- ramls/counterreports.raml
- ramls/usagedataproviders.raml
* Update api versions in raml files
* Add new methods to ModuleDescriptor
* Update interface version in ModuleDescriptor
> Update versions from MODEUS-61, MODEUS-63

- mod-erm-usage-server/src/main/resources/templates/db_scripts/schema.json
…to 3.0.0 to execute sql when upgrading module
> [MODEUS-93] Fix fromModuleVersion of counterreports_trigger.sql

- mod-erm-usage-server/src/main/resources/templates/db_scripts/migration/4.0.0/migration.sql
- mod-erm-usage-server/src/main/resources/templates/db_scripts/schema.json
https://issues.folio.org/browse/MODEUS-110
> MODEUS-110: Add migration script and steps for v4

- descriptors/ModuleDescriptor-template.json
Increase default container memory
> MODEUS-121

- mod-erm-usage-client/pom.xml
- pom.xml
(MODEUS-113, MODEUS-116, MODEUS-120, UIEUS-243)
> Upgrade mod-erm-usage-counter to v2.2.0

- descriptors/ModuleDescriptor-template.json
- ramls/schemas/udprovider.json
- ramls/usagedataproviders.raml
PR in preparation for [UIEUS-266](https://issues.folio.org/browse/UIEUS-266).
Make some properties of UsageDataProvider to not required.
> MODEUS-123

- pom.xml
Updates mod-erm-usage-counter library to v2.2.1, which fixes an error when uploading reports.
> MODEUS-124

- mod-erm-usage-server/src/main/java/org/folio/rest/util/ReportExportHelper.java
- mod-erm-usage-server/src/test/java/org/folio/rest/impl2/CounterReportExportIT.java
- mod-erm-usage-server/src/test/java/org/folio/rest/impl2/CounterReportExportStandardViewIT.java
- mod-erm-usage-server/src/test/java/org/folio/rest/util/ReportExportHelperTest.java
Appends "via FOLIO eUsage app" to `Created_By` value in C5 CSVs.
> MODEUS-130

- mod-erm-usage-server/src/main/resources/templates/db_scripts/counterreports_triggers.sql
- mod-erm-usage-server/src/test/java/templates/db_scripts/SQLTriggersIT.java
Fixes duplicate error codes on usage data providers.
> MODEUS-129

- mod-erm-usage-server/src/main/resources/templates/db_scripts/custom_indexes.sql
- mod-erm-usage-server/src/main/resources/templates/db_scripts/schema.json
Updates `schema.json` for module upgrade.
> MODEUS-127-schema-migration

- pom.xml
Increase mod-erm-usage-counter version to v2.2.2
> MODEUS-132

- mod-erm-usage-server/pom.xml
- pom.xml
Updates dependencies to RMB 33.2.1, vert.x 4.2.1 and aspectj 1.9.7.
> MODEUS-133

- pom.xml
> MODEUS-134

- pom.xml
https://stackoverflow.com/a/4725728
> MODEUS-144: Publish javadoc and sources to maven repository

- NEWS.md
- mod-erm-usage-client/pom.xml
- mod-erm-usage-server/pom.xml
- pom.xml
> tmp-release

- pom.xml
For Orchid upgrade
* RMB from 35.0.1 to 35.0.5 and
* Vert.x from 4.3.4 to 4.3.7.
This provides several bug fixes.
> MODEUS-155: RMB 35.0.5, Vert.x 4.3.7

- mod-erm-usage-server/src/main/java/org/folio/rest/util/ReportExportHelper.java
- mod-erm-usage-server/src/main/java/org/folio/rest/util/UploadHelper.java
- mod-erm-usage-server/src/test/java/org/folio/rest/impl2/CounterReportSortedIT.java
- pom.xml
Upgrade mod-erm-usage-counter dependency to v3
Replace gson usages
> MODEUS-158

- mod-erm-usage-server/src/main/java/org/folio/rest/util/UploadHelper.java
- mod-erm-usage-server/src/test/java/org/folio/rest/impl2/CounterReportUploadIT.java
- mod-erm-usage-server/src/test/java/org/folio/rest/util/UploadHelperTest.java
- mod-erm-usage-server/src/test/resources/fileupload/brill_tr.json
- mod-erm-usage-server/src/test/resources/fileupload/reportCOP5TRMultiMonth.json
Limit upload of counter5 reports to specific master reports
> MODEUS-159

- mod-erm-usage-server/src/main/java/org/folio/rest/impl/CounterReportAPI.java
- mod-erm-usage-server/src/main/java/org/folio/rest/util/ReportExportHelper.java
- mod-erm-usage-server/src/main/java/org/folio/rest/util/RowStreamHandlerR4.java
- mod-erm-usage-server/src/main/java/org/folio/rest/util/RowStreamHandlerR5.java
Reduces memory consumption during multi month exports by using `PostgresClient.selectReadStream` with `chunkSize=1` to retrieve and merge one report at a time
> MODEUS-165

- sample-data/counter-reports/2018-03.json
Fix nesting in sample report JSON
> MODEUS-166

- descriptors/ModuleDescriptor-template.json
- mod-erm-usage-server/src/main/resources/templates/db_scripts/counterreports_triggers.sql
- mod-erm-usage-server/src/main/resources/templates/db_scripts/migration/5.0.0/migrate_update_udp_stats.sql
- mod-erm-usage-server/src/main/resources/templates/db_scripts/schema.json
- mod-erm-usage-server/src/test/java/templates/db_scripts/SQLTriggersIT.java
- ramls/schemas/udprovider.json
https://folio-org.atlassian.net/browse/MODEUS-182
Adds information about counter report release versions associated with a usage data provider for filtering purposes.
* Update udprovider schema
* Update statistics trigger/functions
* Add migration script
* Add tests for statistics update
* Rework SQLTriggersIT test
> [MODEUS-182] Add report releases summary to UDP schema

- .github/workflows/postgres.yml
- descriptors/ModuleDescriptor-template.json
- mod-erm-usage-server/src/main/java/org/folio/rest/impl/AggregatorSettingsAPI.java
- mod-erm-usage-server/src/main/java/org/folio/rest/impl/CounterReportAPI.java
- mod-erm-usage-server/src/main/java/org/folio/rest/impl/CustomReportAPI.java
- mod-erm-usage-server/src/main/java/org/folio/rest/impl/UsageDataProvidersAPI.java
- pom.xml
- ramls/aggregatorsettings.raml
- ramls/counterreports.raml
- ramls/customreports.raml
- ramls/files.raml
- ramls/usagedataproviders.raml
https://folio-org.atlassian.net/browse/MODEUS-185
* Update RMB, vert.x, aspectj versions
* Update raml-util
* Update API method parameters (remove `lang`, add `totalRecords`)
* Add GA postgres workflow
> [MODEUS-185] Upgrade RMB to v35.3.0

- descriptors/ModuleDescriptor-template.json
Interface version was increased twice. Should be `3.0` instead of `3.1`.
> Fix usage-data-providers interface version

- NEWS.md
- mod-erm-usage-client/pom.xml
- mod-erm-usage-server/pom.xml
- pom.xml
https://folio-org.atlassian.net/browse/MODEUS-186
Release v5.0.0
> [MODEUS-186] Release v5.0.0

- mod-erm-usage-server/src/main/java/org/folio/rest/util/ClockProvider.java
- mod-erm-usage-server/src/main/java/org/folio/rest/util/ReportExportHelper.java
- mod-erm-usage-server/src/test/java/org/folio/rest/impl/CounterReportExportIT.java
- mod-erm-usage-server/src/test/java/org/folio/rest/util/ReportExportHelperTest.java
https://folio-org.atlassian.net/browse/MODEUS-194
> [MODEUS-194] Set `Created` date when exporting reports as CSV/XLSX

- mod-erm-usage-server/src/main/java/org/folio/rest/impl/CounterReportAPI.java
- mod-erm-usage-server/src/main/java/org/folio/rest/util/ReportFileFormat.java
- mod-erm-usage-server/src/main/java/org/folio/rest/util/ReportReleaseVersion.java
- mod-erm-usage-server/src/main/java/org/folio/rest/util/UploadHelper.java
- mod-erm-usage-server/src/test/java/org/folio/rest/impl2/CounterReportMultipartuploadIT.java
- mod-erm-usage-server/src/test/java/org/folio/rest/util/ReportFileFormatTest.java
- mod-erm-usage-server/src/test/java/org/folio/rest/util/ReportReleaseVersionTest.java
- mod-erm-usage-server/src/test/java/org/folio/rest/util/UploadHelperTest.java
https://folio-org.atlassian.net/browse/MODEUS-197
* Refactors `UploadHelper` class
* Considers file extension of uploaded files to determine the report format
> [MODEUS-197] Refactor `UploadHelper`

- pom.xml
https://folio-org.atlassian.net/browse/MODEUS-200
* Updates `maven-surefire-plugin` and `maven-failsafe-plugin` to `v3.5.2`
> [MODEUS-200] Update `maven-surefire-plugin` and `maven-failsafe-plugin`

- NEWS.md
- mod-erm-usage-client/pom.xml
- mod-erm-usage-server/pom.xml
- pom.xml
https://folio-org.atlassian.net/browse/MODEUS-201
> [MODEUS-201] Release v5.1.0

- descriptors/ModuleDescriptor-template.json
- mod-erm-usage-server/src/main/resources/templates/db_scripts/migration/5.2.0/migrate_udp_schema.sql
- mod-erm-usage-server/src/main/resources/templates/db_scripts/schema.json
- mod-erm-usage-server/src/main/resources/templates/db_scripts/usage_data_providers.sql
- mod-erm-usage-server/src/test/java/org/folio/rest/impl2/UsageDataProvidersIT.java
- ramls/examples/udproviders.sample
- ramls/examples/udproviders2.sample
- ramls/examples/udproviders_collection.sample
- ramls/schemas/udprovider.json
- sample-data/usage-data-providers/SAMPLE_R4.json
- sample-data/usage-data-providers/SAMPLE_R51.json
https://folio-org.atlassian.net/browse/MODEUS-204
* Updates schema
* Adds DB constraint
* Adds migration script
* Updates schema examples and sample data
> [MODEUS-204] Add 'status' field to UDP schema

- mod-erm-usage-server/src/main/resources/templates/db_scripts/schema.json
https://folio-org.atlassian.net/browse/MODEUS-205
> [MODEUS-205] Add `likeIndex` for `status`

- mod-erm-usage-server/src/main/resources/templates/db_scripts/schema.json
https://folio-org.atlassian.net/browse/MODEUS-205
> [MODEUS-205] Use `fullTextIndex` for `status` to be consistent with other attributes
